<script lang="ts">
	// The mission picker: each card is one big question, fronted by a portrait
	// of the body the question is about (generated by
	// `npm run preset-screenshots -- --missions`) and tinted with the mission's
	// own color — the question is the mission, so it's the whole card.
	//
	// Picking a mission doesn't load it yet: it flips to the prediction step,
	// and choosing a prediction is what commits. The prediction is the point of
	// the exercise (it's what makes watching the sim an observation rather than
	// a demo), so there's no way to start a mission without making one. It is
	// never scored, and never shown back against the outcome — the comparison
	// is the student's to make.
	//
	// The prediction is deliberately the *only* thing here. The what-to-do
	// instructions used to share this dialog as a second numbered step, and
	// read as a block of text to memorize before the controls existed; they now
	// live in the in-app mission panel as a checklist that points at the
	// controls themselves (see MissionSteps and state/missionGuide.svelte.ts).

	import { MISSIONS, choiceLetter, type Mission } from "../presets/missions";
	import { mission as missionState } from "../state/mission.svelte";
	import { fade, scale } from "svelte/transition";
	import { DIALOG_MS, DIALOG_SCALE, duration } from "./motion";

	// The list renders in sections: consecutive missions sharing a `category`
	// fall under one heading. MISSIONS keeps each category contiguous (tested),
	// so this is a single pass, and it's static — computed once, not reactive.
	const sections: { category: string; missions: Mission[] }[] = [];
	for (const m of MISSIONS) {
		const last = sections[sections.length - 1];
		if (last?.category === m.category) last.missions.push(m);
		else sections.push({ category: m.category, missions: [m] });
	}

	interface Props {
		onpick: (mission: Mission, prediction: number) => void;
		onclose: () => void;
	}

	let { onpick, onclose }: Props = $props();

	/** Mission whose prediction question is showing, or null for the list. */
	let predicting = $state<Mission | null>(null);

	/** Mission ids whose portrait failed to load — drawn as a color wash instead. */
	let missing = $state<Record<string, boolean>>({});

	/**
	 * Whether the reset button is asking for confirmation. Clearing the tally
	 * can't be undone, so it takes two clicks rather than a `confirm()` dialog —
	 * the button becomes its own confirmation in place.
	 */
	let confirmingReset = $state(false);

	function resetProgress() {
		missionState.resetProgress();
		confirmingReset = false;
	}

	function portraitUrl(id: string): string {
		return `${import.meta.env.BASE_URL}missions/${id}.jpg`;
	}

	/** Missions still to go before this one unlocks — same as PresetDialog. */
	function lockedBy(m: Mission): number {
		if (m.unlockAfterMissions === undefined) return 0;
		return Math.max(0, m.unlockAfterMissions - missionState.completedCount);
	}
</script>

<svelte:window
	onkeydown={(e) => {
		if (e.key !== "Escape") return;
		// Escape backs out one step at a time: reset confirmation → prediction →
		// list → closed. The confirmation goes first so Escape never closes the
		// dialog while an irreversible action is waiting on an answer.
		if (confirmingReset) confirmingReset = false;
		else if (predicting !== null) predicting = null;
		else onclose();
	}}
/>

<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
<div
	class="backdrop"
	role="presentation"
	onclick={(e) => {
		if (e.target === e.currentTarget) onclose();
	}}
	transition:fade={{ duration: duration(DIALOG_MS) }}
>
	<div
		class="dialog"
		role="dialog"
		aria-modal="true"
		aria-label="Load mission"
		transition:scale={{ duration: duration(DIALOG_MS), start: DIALOG_SCALE, opacity: 0 }}
	>
		<header>
			{#if predicting !== null}
				<button class="back" onclick={() => (predicting = null)}>‹ Back</button>
				<h2 style:color={predicting.color}>{predicting.name}</h2>
			{:else}
				<h2>Missions</h2>
			{/if}
			<button class="close" onclick={onclose} aria-label="Close">×</button>
		</header>

		<!-- Progress lives at the top of the list, where it reads as a heading for
         the cards below rather than a footnote under them. The reset control
         sits with it because it acts on exactly this number. Hidden on the
         prediction step, which is about one mission, not the set. -->
		{#if predicting === null}
			<div class="progress-bar">
				<div
					class="track"
					role="progressbar"
					aria-valuenow={missionState.completedCount}
					aria-valuemin="0"
					aria-valuemax={MISSIONS.length}
					aria-label="Missions completed"
				>
					<div class="bar-fill" style:width="{(missionState.completedCount / MISSIONS.length) * 100}%"></div>
				</div>
				{#if confirmingReset}
					<!-- Replaces the count while armed: clearing can't be undone, so the
               warning takes the space rather than sitting somewhere else. -->
					<span class="warn">Clear all {missionState.completedCount}? Can't be undone.</span>
				{:else}
					<span class="count">
						<strong>{missionState.completedCount}</strong> / {MISSIONS.length}
					</span>
				{/if}
				{#if missionState.completedCount > 0}
					{#if confirmingReset}
						<button class="reset confirm" onclick={resetProgress}>Clear</button>
						<button class="reset" onclick={() => (confirmingReset = false)}>Cancel</button>
					{:else}
						<button class="reset" onclick={() => (confirmingReset = true)} title="Forget every completed mission">
							Reset
						</button>
					{/if}
				{/if}
			</div>
		{/if}

		{#if predicting !== null}
			<!-- Committing to an answer is what makes the run an observation rather
           than a demo, so the prediction comes before anything that could hint
           at the outcome — and it's all this dialog asks. Picking a choice is
           what starts the mission. -->
			<div class="predict" style:--mission-color={predicting.color}>
				<p class="big-question">{predicting.question}</p>
				<p class="prompt">{predicting.predictPrompt}</p>
				<!-- Radio-styled buttons rather than a real radio group: picking is
             the commit, so there's no separate submit for a group to feed. -->
				<div class="choices">
					{#each predicting.choices as choice, index (index)}
						<button class="choice" onclick={() => onpick(predicting!, index)}>
							<!-- The letter is read out, not decoration: the debrief names the
                   outcome by letter, so it has to have been announced here. -->
							<span class="letter">{choiceLetter(index)}</span>
							<span class="text">{choice}</span>
						</button>
					{/each}
				</div>
				<!-- Sets the expectation that nothing needs memorizing: the what-to-do
             steps arrive with the controls they point at. -->
				<p class="start-note">
					Pick the one you expect — the mission starts right away, with step-by-step instructions beside the controls.
				</p>
			</div>
		{:else}
			<div class="list">
				{#each sections as section (section.category)}
					<h3 class="category">{section.category}</h3>
					{#each section.missions as mission (mission.id)}
						{@const remaining = lockedBy(mission)}
						{@const done = missionState.isCompleted(mission.id)}
						<button
							class="card"
							class:locked={remaining > 0}
							class:done
							disabled={remaining > 0}
							style:--mission-color={mission.color}
							onclick={() => {
								// Leaving the list disarms the confirmation — coming back to a
								// still-armed "Clear progress" would be a trap.
								confirmingReset = false;
								predicting = mission;
							}}
						>
							<span class="portrait" aria-hidden="true">
								{#if !missing[mission.id]}
									<img
										src={portraitUrl(mission.id)}
										alt=""
										loading="lazy"
										onerror={() => (missing = { ...missing, [mission.id]: true })}
									/>
								{/if}
								{#if remaining > 0}
									<span class="lock" aria-hidden="true">🔒</span>
								{:else if done}
									<span class="stamp" aria-hidden="true">✓</span>
								{/if}
							</span>
							<span class="body">
								<span class="name">
									<span class="chip">{mission.name}</span>
									{#if done}
										<span class="done-pill">✓ Completed</span>
									{/if}
								</span>
								<span class="big-question">{mission.question}</span>
								{#if remaining > 0}
									<span class="lock-note">
										Locked — complete {remaining} more {remaining === 1 ? "mission" : "missions"}
										to unlock.
									</span>
								{/if}
							</span>
						</button>
					{/each}
				{/each}
			</div>
		{/if}
	</div>
</div>

<style>
	.backdrop {
		position: fixed;
		inset: 0;
		background: rgba(0, 0, 0, 0.55);
		display: flex;
		align-items: center;
		justify-content: center;
		z-index: 10;
		/* `inset: 0` on a fixed element already tracks the *visible* viewport as
       mobile browser chrome comes and goes, so the height is left to it — an
       explicit `100vh` here would size against the URL-bar-hidden viewport and
       push the dialog partly off screen. The padding is what holds the dialog
       off the edges, so the dialog itself just caps at 100% of this box.
       The `max()` keeps a notch or home indicator from eating that margin. */
		padding: max(24px, env(safe-area-inset-top)) 16px max(24px, env(safe-area-inset-bottom));
		box-sizing: border-box;
	}

	.dialog {
		width: 740px;
		/* The backdrop's padding is what holds the dialog off the edges now, so the
       dialog is capped against its parent rather than against the viewport. */
		max-width: 100%;
		max-height: 100%;
		display: flex;
		flex-direction: column;
		/* A flex item won't shrink below its content unless told to. Without this
       the dialog grows past max-height and the scroll region below never
       scrolls — it just overflows, clipping the footer. */
		min-height: 0;
		background: var(--bg-panel);
		border: 1px solid var(--border);
		border-radius: 14px;
		box-shadow: 0 16px 48px rgba(0, 0, 0, 0.6);
	}

	header {
		display: flex;
		align-items: center;
		gap: 10px;
		/* Never shrink: the header is how you close the dialog. */
		flex: none;
		padding: 14px 16px;
		border-bottom: 1px solid var(--border);
	}

	h2 {
		flex: 1;
		margin: 0;
		font-size: 20px;
		font-weight: 700;
	}

	.back {
		flex: none;
		font-size: 15px;
		font-weight: 600;
		padding: 5px 12px;
		border-radius: 8px;
		color: var(--text-dim);
		background: transparent;
		border-color: transparent;
	}

	.back:hover {
		color: var(--text);
		border-color: var(--border);
	}

	.close {
		background: none;
		border: none;
		font-size: 24px;
		line-height: 1;
		color: var(--text-dim);
		padding: 0 6px;
	}

	.close:hover {
		color: var(--text);
	}

	/* The two scrolling regions. `min-height: 0` is the load-bearing line in
     both: it's what lets them shrink inside the flex column so the overflow
     resolves as a scrollbar instead of a clipped dialog. `-webkit-overflow-
     scrolling` keeps momentum scrolling on older iOS Safari, and
     `overscroll-behavior: contain` stops a scroll that runs off the end of the
     list from chaining through to the page (and, on the canvas behind, from
     turning into a pinch-zoom of the whole app). */
	.list,
	.predict {
		flex: 1 1 auto;
		min-height: 0;
		overflow-y: auto;
		-webkit-overflow-scrolling: touch;
		overscroll-behavior: contain;
	}

	.list {
		padding: 14px;
		display: flex;
		flex-direction: column;
		gap: 10px;
	}

	/* Section headings share the cards' flex column; the top margin (on top of
     the column gap) is what visually opens a new section, so the first one —
     which has no section above it — drops it. */
	.category {
		margin: 8px 0 0;
		font-size: 12px;
		font-weight: 700;
		letter-spacing: 0.08em;
		text-transform: uppercase;
		color: var(--text-dim);
	}

	.category:first-child {
		margin-top: 0;
	}

	/* Cards carry their mission color as a tinted fill and a name chip rather
     than an accent stripe down one edge — the portrait and the chip are what
     tell the experiments apart, so the border stays neutral. */
	.card {
		display: flex;
		align-items: stretch;
		/* The list is a flex column, so a card is a flex item and will otherwise
       shrink to share the list's height between all of them — squeezing the
       text out from under the portrait rather than overflowing into a scroll.
       Cards keep their natural height; the list scrolls. */
		flex: none;
		gap: 0;
		padding: 0;
		text-align: left;
		background: color-mix(in srgb, var(--mission-color) 7%, var(--bg-raised));
		border: 1px solid var(--border);
		border-radius: 14px;
		overflow: hidden;
		transition:
			transform 0.12s ease,
			background-color 0.12s ease;
	}

	.card:hover,
	.card:focus-visible {
		background: color-mix(in srgb, var(--mission-color) 16%, var(--bg-raised));
		border-color: color-mix(in srgb, var(--mission-color) 55%, var(--border));
		transform: translateY(-1px);
	}

	/* Locked cards mirror the preset dialog: greyed portrait under a lock
     glyph, no hover lift, and the caption says what opens them. */
	.card.locked {
		cursor: default;
	}

	.card.locked:hover,
	.card.locked:focus-visible {
		background: color-mix(in srgb, var(--mission-color) 7%, var(--bg-raised));
		border-color: var(--border);
		transform: none;
	}

	.card.locked .portrait img {
		filter: grayscale(1) brightness(0.45);
	}

	.card.locked .big-question {
		color: var(--text-dim);
	}

	.lock {
		position: absolute;
		inset: 0;
		display: flex;
		align-items: center;
		justify-content: center;
		font-size: 22px;
		/* The glyph carries its own colour; dim it to sit on the greyed image. */
		opacity: 0.75;
	}

	.lock-note {
		font-size: 13px;
		color: var(--text-dim);
	}

	/* The portrait column. Fixed width so the cards line up; the color wash
     behind it doubles as the fallback when the image hasn't been generated.
     Relative so the lock glyph can cover exactly it. */
	.portrait {
		position: relative;
		flex: none;
		width: 150px;
		background: color-mix(in srgb, var(--mission-color) 18%, var(--bg-raised));
	}

	.portrait img {
		display: block;
		width: 100%;
		height: 100%;
		object-fit: cover;
	}

	.body {
		flex: 1;
		min-width: 0;
		display: flex;
		flex-direction: column;
		justify-content: center;
		gap: 7px;
		padding: 14px 16px;
	}

	.name {
		display: flex;
		align-items: center;
		gap: 7px;
	}

	/* The mission's color lands here, as a filled pill — legible as a label at
     a glance and readable against the card's own tint. */
	.chip {
		font-size: 13px;
		font-weight: 700;
		padding: 3px 10px;
		border-radius: 999px;
		color: #0a0b0f;
		background: var(--mission-color);
	}

	/* Completed cards. The card itself carries the state — green border and a
     wash over the mission's own tint — so a finished mission is obvious while
     scanning the list, not just once you reach the pill. The portrait dims so
     the check over it stays legible against a bright image. */
	.card.done {
		border-color: color-mix(in srgb, var(--ok) 45%, var(--border));
		background: color-mix(in srgb, var(--ok) 9%, var(--bg-raised));
	}

	.card.done:hover,
	.card.done:focus-visible {
		border-color: color-mix(in srgb, var(--ok) 70%, var(--border));
		background: color-mix(in srgb, var(--ok) 16%, var(--bg-raised));
	}

	/* Corner badge rather than a centerd stamp over a dimmed image: several
     portraits are mostly black space, so dimming them to float a check leaves
     an empty tile. The disc carries its own contrast, so the image is left
     alone. */
	.stamp {
		position: absolute;
		top: 8px;
		left: 8px;
		width: 24px;
		height: 24px;
		display: flex;
		align-items: center;
		justify-content: center;
		font-size: 14px;
		font-weight: 700;
		line-height: 1;
		border-radius: 50%;
		color: #0a0b0f;
		background: var(--ok);
		box-shadow: 0 2px 8px rgba(0, 0, 0, 0.6);
	}

	.done-pill {
		font-size: 11px;
		font-weight: 700;
		letter-spacing: 0.04em;
		text-transform: uppercase;
		padding: 3px 9px;
		border-radius: 999px;
		color: var(--ok);
		background: color-mix(in srgb, var(--ok) 16%, transparent);
		border: 1px solid color-mix(in srgb, var(--ok) 45%, transparent);
		white-space: nowrap;
	}

	.big-question {
		font-size: 17px;
		font-weight: 600;
		line-height: 1.4;
		color: var(--text);
	}

	.predict {
		padding: 18px 16px;
		display: flex;
		flex-direction: column;
		gap: 18px;
	}

	.predict .big-question {
		margin: 0;
		font-size: 22px;
		font-weight: 700;
		line-height: 1.3;
	}

	.prompt {
		margin: 0;
		font-size: 15px;
		color: var(--text-dim);
	}

	/* Stacked, not side by side: the choices are sentences, and three columns of
     a 740 px dialog can't hold one without ragged wrapping. Stacked they also
     read as the radio list they behave like. */
	.choices {
		display: flex;
		flex-direction: column;
		gap: 10px;
	}

	.choice {
		display: flex;
		align-items: center;
		gap: 14px;
		width: 100%;
		padding: 15px 16px;
		text-align: left;
		font-size: 16px;
		line-height: 1.35;
		background: var(--bg-raised);
		border: 1px solid var(--border);
		border-radius: 12px;
		transition:
			background-color 0.12s ease,
			border-color 0.12s ease;
	}

	.choice .text {
		flex: 1;
		min-width: 0;
	}

	/* A lettered badge rather than a radio ring: nothing is ever shown selected
     (picking commits and closes the step), so the marker's job is to name the
     option — the panel and the debrief both refer back to it by letter. */
	.letter {
		flex: none;
		display: flex;
		align-items: center;
		justify-content: center;
		width: 26px;
		height: 26px;
		border-radius: 50%;
		border: 1px solid var(--text-dim);
		font-size: 14px;
		font-weight: 700;
		line-height: 1;
		color: var(--text-dim);
		transition:
			border-color 0.12s ease,
			background-color 0.12s ease,
			color 0.12s ease;
	}

	.choice:hover,
	.choice:focus-visible {
		background: color-mix(in srgb, var(--mission-color) 14%, var(--bg-raised));
		border-color: color-mix(in srgb, var(--mission-color) 60%, var(--border));
	}

	.choice:hover .letter,
	.choice:focus-visible .letter {
		border-color: var(--mission-color);
		background: color-mix(in srgb, var(--mission-color) 30%, transparent);
		color: var(--text);
	}

	.start-note {
		margin: 0;
		font-size: 13px;
		line-height: 1.45;
		color: var(--text-dim);
	}

	/* The progress row: bar, count, and the control that resets them. Sits
     between the header and the list, above the scroll region so it stays put
     while the cards move. */
	.progress-bar {
		flex: none;
		display: flex;
		align-items: center;
		gap: 12px;
		padding: 11px 16px;
		border-bottom: 1px solid var(--border);
	}

	.track {
		flex: 1;
		min-width: 0;
		height: 7px;
		border-radius: 999px;
		background: var(--bg-raised);
		overflow: hidden;
	}

	/* Animated so completing a mission and reopening the picker shows the bar
     move, rather than it having silently jumped. */
	.bar-fill {
		height: 100%;
		border-radius: 999px;
		/* Same green as the cards' completed state — the bar is the tally of
       exactly those cards. */
		background: var(--ok);
		transition: width 0.35s ease;
	}

	.count {
		flex: none;
		font-size: 13px;
		color: var(--text-dim);
		font-variant-numeric: tabular-nums;
	}

	.count strong {
		font-size: 15px;
		color: var(--text);
	}

	.warn {
		flex: none;
		font-size: 13px;
		font-weight: 600;
		color: var(--danger, #ff8080);
	}

	/* Quiet by default — this is a maintenance action sitting next to a progress
     readout, not something to draw the eye away from the missions. */
	.reset {
		flex: none;
		font-size: 13px;
		font-weight: 600;
		padding: 6px 12px;
		border-radius: 8px;
		color: var(--text-dim);
		background: transparent;
	}

	.reset:hover {
		color: var(--text);
		border-color: var(--text-dim);
	}

	/* Armed: the click that actually clears reads as destructive. */
	.reset.confirm {
		color: var(--danger, #ff8080);
		border-color: color-mix(in srgb, var(--danger, #ff8080) 55%, var(--border));
		background: color-mix(in srgb, var(--danger, #ff8080) 14%, transparent);
	}

	.reset.confirm:hover {
		color: #0a0b0f;
		background: var(--danger, #ff8080);
		border-color: var(--danger, #ff8080);
	}

	/* --- narrow viewports -------------------------------------------------
     Two things break on a phone: the card's 150 px portrait column leaves the
     question about 160 px of a 390 px screen, and the choices row divides that
     same width three ways. Both become vertical stacks. */
	@media (max-width: 560px) {
		.backdrop {
			/* Full-bleed: a rounded card floating in a 16 px margin wastes width
         that the questions need. */
			padding: 0;
			padding-top: env(safe-area-inset-top);
			padding-bottom: env(safe-area-inset-bottom);
		}

		.dialog {
			border-radius: 0;
			border-left: none;
			border-right: none;
		}

		header {
			padding: 12px;
		}

		h2 {
			font-size: 17px;
		}

		/* The portrait moves above the text and becomes a letterbox banner, so the
       question gets the full width. */
		.card {
			flex-direction: column;
		}

		/* A fixed banner height rather than an aspect ratio: a ratio against the
       full card width resolves to ~230 px, which crowds the question off a
       phone screen. */
		.portrait {
			width: auto;
			height: 104px;
			flex: none;
		}

		.body {
			padding: 12px;
		}

		.list {
			padding: 10px;
		}

		.predict {
			padding: 14px 12px;
		}

		.predict .big-question {
			font-size: 19px;
		}

		.choice {
			gap: 12px;
			padding: 13px 14px;
			font-size: 15px;
		}

		.progress-bar {
			gap: 10px;
			padding: 10px 12px;
		}

		/* Armed, the warning plus two buttons need a row of their own; the bar
       takes the full width above them. */
		.progress-bar:has(.warn) {
			flex-wrap: wrap;
		}

		.progress-bar:has(.warn) .track {
			flex: 1 0 100%;
		}

		.progress-bar:has(.warn) .warn {
			flex: 1;
		}
	}
</style>
